#!/bin/sh

# Flush all rules
bspc rule -r "*"

# Colors
background=$(xrdb -query | grep "background" | cut -f2 | sed -r 's/#//' | head -n 1)
foreground=$(xrdb -query | grep "foreground" | cut -f2 | sed -r 's/#//' | head -n 1)
color0=$(xrdb -query | grep "color0" | cut -f2 | sed -r 's/#//' | head -n 1)
color1=$(xrdb -query | grep "color1" | cut -f2 | sed -r 's/#//' | head -n 1)
color2=$(xrdb -query | grep "color2" | cut -f2 | sed -r 's/#//' | head -n 1)
color3=$(xrdb -query | grep "color3" | cut -f2 | sed -r 's/#//' | head -n 1)
color4=$(xrdb -query | grep "color4" | cut -f2 | sed -r 's/#//' | head -n 1)
color5=$(xrdb -query | grep "color5" | cut -f2 | sed -r 's/#//' | head -n 1)
color6=$(xrdb -query | grep "color6" | cut -f2 | sed -r 's/#//' | head -n 1)
color7=$(xrdb -query | grep "color7" | cut -f2 | sed -r 's/#//' | head -n 1)
color8=$(xrdb -query | grep "color8" | cut -f2 | sed -r 's/#//' | head -n 1)

bspc config normal_border_color "#$color9"
bspc config active_border_color "#$color8"
bspc config focused_border_color "#$color8"
bspc config presel_feedback_color "#$color1"

# Workspaces
bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 
bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9

# Common configuration
bspc config border_width        1
bspc config window_gap          8
bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     false
bspc config focus_follows_pointer true
bspc config top_padding         24  # polybar's height
bspc config bottom_padding      0
bspc config left_padding        0
bspc config right_padding       0

pkill sxhkd
sxhkd > /tmp/sxhkd.log 2>&1 &

# Fix cursor
xsetroot -cursor_name left_ptr

# Launch polybar
launch_polybar

